### PR TITLE
Tidy gcsweb HTML

### PR DESCRIPTION
**Pull request by nebril**
Small refactor of rendering functions
Add minimal pure css framework for buttons and grid
Changed tables to pure grids

### CODE REVIEW

**Comment by thockin** [comment]
This is much improved.  I am going to merge it and revisit this PR (probably should not be in contrib any more :)

Thanks.

For iteration:
- would be nice to be more compact with whitespace
- we should add directory and file icons :)

**Comment by thockin** [comment]
Also would be nice to bold or underline column headers.  I can do that manually with <u> - is that the best way?

**Comment by nebril** [comment]
@thockin please let me know where will this project live, after that I can contribute to it :)
About underlining headers - you should probably apply `border: bottom 1px solid` style to all header items (thanks to grid layout the border should be aligned nicely).

**Comment by thockin** [comment]
https://github.com/kubernetes/test-infra/pull/728

**Comment by thockin** [comment]
I don't know how to do that.  patches welcome :)

**Pull request merged**
